### ISSUE TITLE
TODO #3_'/detail 페이지' 구현

### ISSUE THREAD

**Issue by Mandoremee** [CSID-DGU/3S1C_frontend#12]
*상세 페이지 구현
- 아래 내용을 바탕으로 API 스펙 확정 필요

- 상단 바 내용
- [ ] 현재 페이지에서 보고 있는 키워드
- [ ] 키워드에 따른 백그라운드 이미지 (출처를 어떻게 할지... 어렵다면 그냥 디자인 ㄱㄱ)

- 슬라이드 가능한 시각화 자료 보기
- [ ] 관심 성비 바 차트
- [ ] 관심 연령대 바 차트
- [ ] 감성분석 파이 차트 (긍/부 or 희노애락 or 둘 다)
- [ ] 워드클라우드 (메인 키워드 & 연관 키워드 / 크기 가중치 결정식 확정 및 연관 키워드 개수 논의)
- [ ] 댓글 작성 시간분포 라인 차트(or 바 차트)
- [ ] 추가적인 '본 프로젝트만의 독창적인 분석 결과'에 대한 시각화 **생각해보자!**

- 유저코멘트 기능(?)
- [ ] 댓글 작성하기 or 좋아요 버튼
