### ISSUE TITLE
TODO #4_기획 분석 페이지 구현

### ISSUE THREAD

**Issue by Mandoremee** [CSID-DGU/3S1C_frontend#13]
###기획 분석 페이지 구현

- [ ] 키워드 관련 이미지의 수집처 결정 및 수집 방법 구현
(이미지 여러개를 바둑판 형식으로 묶어서 평준화 할지 아니면 대표로 하나만 할지)
- [ ] 색채 추출 알고리즘으로 수집 이미지 분석 절차까지 자동화
- [ ] DB로 저장(추출한 이미지 원본 or 블러 처리(저작권때문) & 추출 색상의 크로마토그래피)
- [ ] 추출된 색상에 가장 가까운 "이름이 있는 색" 찾기 알고리즘 & 태깅
(각 "이름이 있는 색"에 대한 색채심리학적 사실, 효과 등에 대한 데이터베이스 정립 필요)
- [ ] 키워드, 이미지, 색채 크로마토그래피, 색채의 효과 및 사실에 대한 시각화
- [ ] 색채의 효과 및 사실 <-> 키워드의 감성 분석 결과 사이의 상관관계 분석 및 코멘트

크롤링 ~ 파이썬 실행 ~ 디비 저장까지의 과정이 요구될 것
