### ISSUE TITLE
TODO #6_사이드 바 > 건의사항 보내기

### ISSUE THREAD

**Issue by Mandoremee** [CSID-DGU/3S1C_frontend#15]
- [ ] 'QnA'를 '건의사항 보내기'로 바꾸기
- [ ] 글 쓸 수 있는 공간에 적힌 내용을 아래 commit 버튼으로 DB로 보낼 수 있게 만들기
- [ ] 개발자가 확인할 수 있는 방법(페이지를 따로 파든, 그냥 디비로 보든) 결정
- [ ] 건의사항 피드백 공지 페이지(심플하게) 만들기 >> 옵션사항

**Comment by Mandoremee** [comment]
2. db보다는 administrator계정을 인식하고 게시판 혹은 리스트 형식으로 보여주는게 좋을 것 같음.
